services:
  db:
    image: postgres:16-alpine
    container_name: spotify_db
    environment:
      - POSTGRES_USER=spotify_user
      - POSTGRES_PASSWORD=spotify_pwd
      - POSTGRES_DB=spotify_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spotify_user -d spotify_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - spotify_network

volumes:
  pgdata:

networks:
  spotify_network:
    driver: bridge
    name: spotify_network
